### ISSUE TITLE
torch shape mismatch while training the language model.

### ISSUE THREAD

**Issue by BlankSama** [eyalmazuz/MolGen#4]
hi,
While training the language model , Iam facing the torch shape mismatch error:

I have attached the screenshot for the same.

please help

![image](https://github.com/eyalmazuz/MolGen/assets/40503102/ebca8db9-eb46-4b30-935a-35cc55917b6d)

**Comment by eyalmazuz** [comment]
You need to use the gdb13ScaffoldCharTokenizer

**Comment by BlankSama** [comment]
Hi,

I changed the Tokeniser but now facing error in the encoding 

![image](https://github.com/eyalmazuz/MolGen/assets/40503102/cb61343e-b180-4a78-9162-80f32e75a22a)


is this error  because of dataset format as the error mention it is not able to tokenise '\t'.
iam attaching the screenshot of dataset

![image](https://github.com/eyalmazuz/MolGen/assets/40503102/15443fa3-bc6c-42ac-8dac-a38d07696ce6)

Thank you
