### ISSUE TITLE
A question about src/train/reinforcement.py.

### ISSUE THREAD

**Issue by gihanpanapitiya** [eyalmazuz/MolGen#5]
Hello,

Have a question about lines 71 to 78 in src/train/reinforcement.py.
At the end of the for loop at line 70, length of `batch_rewards`  is 500 and that of `batch_tokens` is 50.
Then when you use these `batch_tokens` and `batch_rewards` line 80, aren't the last `batch_tokens` zipped with the first  `batch_rewards`? Is this Ok?

https://github.com/eyalmazuz/MolGen/blob/a892804d44c64b72725d33fd880d477b2e67277a/MolGen/src/train/reinforcement.py#L78

**Comment by eyalmazuz** [comment]
you're correct, since it's batched mode we need to also keep track of the generated tokens and not only the rewards

the issue was fixed
